services:
  voice-analyzer:
    container_name: voice-analyzer-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
      - ./sample:/sample
      - ./models:/root/.cache/huggingface
      - ./logs:/logs
    environment:
      - TZ=Asia/Tokyo
      - LOG_LEVEL=DEBUG
      - ENV=development
      - LOG_BACKUP_COUNT=14
      - LOG_DIR=/logs
    networks:
      - voice_analysis_network

networks:
  voice_analysis_network:
    driver: bridge
